### ISSUE TITLE
componentWillMount vs componentDidMount

### ISSUE THREAD

**Issue by vladamx** [tkh44/react-localforage#1]
Hi,

Don't know if this is the right place to ask this kind of question, but i will take the risk.

I have a question related to this piece of code:

https://github.com/tkh44/react-localforage/blob/873f1d9308787e4fdfd466d3bf2f1690a518a4e8/src/index.js#L27

Can you explain why this call was made in componentWillMount as opposed to componentDidMount?

Can you talk about pros and cons?

Thank you.

**Comment by tkh44** [comment]
I want to process to start before the component is mounted and set the initial state before the first render. [This does a pretty good job of explaining it.](https://developmentarc.gitbooks.io/react-indepth/content/life_cycle/birth/premounting_with_componentwillmount.html)

**Comment by vladamx** [comment]
Yeah. I was thinking that calling setState() on component which is not yet mounted would cause problems.
